#!/usr/bin/env bash
# Print "Best school" 10 times with while loop
# But also print "Hi" the 9th time

i=1
while [ $i -le 10 ]
do 
    echo "Best School"; 
    if [ $i -eq 9 ]
    then
        echo "Hi";
    fi
    (("i++"));
done
